version: "3"
services:
  backend:
    image: ${IMAGE_NAME}
    restart: on-failure:5 # Try 5 restarts after failure
    env_file:
      - .env
    environment:
      - PROJECT_NAME # Comes from Makefile
      - SERVICE_NAME # Comes from Makefile
      - PORT=8080 # Serve always on this port inside container
    ports:
      - ${PORT:-0}:8080
    volumes:
      - ${DATA_PATH:-./data}:/app/data
      - ${UPLOADS_PATH:-./uploads}:/app/uploads
    # Container logging
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "100"
